### ISSUE TITLE
Running deploy causes "fetch is not defined" error

### ISSUE THREAD

**Issue by travs** [paritytech/js-api#1]
Getting an error when trying to deploy a contract, which I did not get when using `parity.js` from the main `paritytech/parity` repo.

Happens when running via a script with `babel-node`, or just via the `node` repl.

Part of the code I am running:

```js
// bytecode and contract previously defined, and api set up as in readme
contract.deploy({data: bytecode}, args)
.catch(err => console.log(err.stack));
```

Stack trace:

```
ReferenceError: fetch is not defined
    at Http._execute (/home/travis/prg/protocol/node_modules/@parity/api/transport/http/http.js:53:5)
    at Http.send (/home/travis/prg/protocol/node_modules/@parity/api/provider/http.js:28:8)
    at Promise (/home/travis/prg/protocol/node_modules/@parity/api/provider/promise.js:42:21)
    at Promise (<anonymous>)
    at PromiseProvider.send (/home/travis/prg/protocol/node_modules/@parity/api/provider/promise.js:41:12)
    at Eth.estimateGas (/home/travis/prg/protocol/node_modules/@parity/api/rpc/eth/eth.js:65:8)
    at Contract.deployEstimateGas (/home/travis/prg/protocol/node_modules/@parity/api/contract/contract.js:115:8)
    at Contract.deploy (/home/travis/prg/protocol/node_modules/@parity/api/contract/contract.js:129:28)
    at Object.deploy (/home/travis/prg/protocol/deployer.js:13:19)
    at _callee$ (/home/travis/prg/protocol/deploy.js:12:46)
```

So it may be due to [this function](https://github.com/paritytech/js-api/blob/1c7cc5561c4e8db0d0b58f22d8bc8baa243909a5/transport/http/http.js#L53) not being defined in the global scope somehow (though it seems to be defined when I install from the other repo).

**Comment by jacogr** [comment]
Was due to the polyfill missing, re-added when Node is detected.
