### ISSUE TITLE
Error when deploying library

### ISSUE THREAD

**Issue by travs** [paritytech/js-api#2]
Trying to deploy via `sendTransaction` while #1 is still occurring for me.

Running the code below:

```
// abi and bytecode already defined
// api constructed as in readme
contract = api.newContract(abi)
encodedOpts = contract._encodeOptions(contract.constructors[0], {data: bytecode}, [])
api.eth.sendTransaction(encodedOpts)
```

Error I received:

```
Error: Cannot convert DataFeedInterface to valid ParamType
    at i (/home/travis/prg/protocol/node_modules/@parity/parity.js/library.js:1:30744) 
    at new t (/home/travis/prg/protocol/node_modules/@parity/parity.js/library.js:1:55667)
    at /home/travis/prg/protocol/node_modules/@parity/parity.js/library.js:1:55873
    at Array.map (<anonymous>)
    at Function.value (/home/travis/prg/protocol/node_modules/@parity/parity.js/library.js:1:55833)
    at new t (/home/travis/prg/protocol/node_modules/@parity/parity.js/library.js:1:42315)     
    at /home/travis/prg/protocol/node_modules/@parity/parity.js/library.js:1:93191
    at Array.map (<anonymous>)
    at Function.value (/home/travis/prg/protocol/node_modules/@parity/parity.js/library.js:1:93045)          
    at e.t (/home/travis/prg/protocol/node_modules/@parity/parity.js/library.js:1:92299)
```

Contract's ABI:

```
[ { constant: true,                                                                            
    inputs: [ [Object] ],                                                                      
    name: 'grossAssetValue',                                                                   
    outputs: [ [Object] ],                                                                     
    payable: false,                                                                            
    stateMutability: 'view',                                                                   
    type: 'function' },                                                                        
  { constant: true,                                                                            
    inputs: [ [Object], [Object], [Object], [Object] ],                                        
    name: 'priceForNumBaseShares',                                                             
    outputs: [ [Object] ],                                                                     
    payable: false,                                                                            
    stateMutability: 'view',                                                                   
    type: 'function' },                                                                        
  { constant: true,                                                                            
    inputs: [ [Object], [Object] ],                                                            
    name: 'netAssetValue',                                                                     
    outputs: [ [Object] ],                                                                     
    payable: false,                                                                            
    stateMutability: 'view',
    type: 'function' } ]
```

Bytecode is [here](https://gist.github.com/travs/6f1718a1d60633d6f697fc67f1945d9e).

**Comment by jacogr** [comment]
Ok, this one is weird. Thanks for the Bytecode/ABI, will need to delve in to see where it breaks.

**Comment by jacogr** [comment]
@travs Could you please supply the ABI without the `[Object]` as part of the inputs/outputs? (i.e. full json)

**Comment by travs** [comment]
@jacogr 
We may have changed a few things since I posted this, so not sure if this will still fail for you.
Will supply the bytecode again as well:

- [bytecode](https://gist.github.com/f6e5b192d4c5fd25637f0ba666b7bdbf)
- [abi](https://gist.github.com/anonymous/63228d50dd4ff7d5d1687c97a8e35a9b)
